//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Data.Entity;

    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.Rentals = new HashSet<Rental>();
        }
    
        public int CarId { get; set; }

        [Required(ErrorMessage = "Manufacturer is Required")]
        public string Manufacturer { get; set; }

        [Required(ErrorMessage = "Model is Required")]
        public string Model { get; set; }

        [Display(Name = "License Plate")]

        [Required(ErrorMessage = "License Plate is Required")]
        public string LicensePlate { get; set; }
        public Nullable<int> Year { get; set; }

        [DefaultValue(true)]
        [Required(ErrorMessage = "Available is Required")]
        public Nullable<bool> Available { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rental> Rentals { get; set; }
    }
}
