//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentACar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rental
    {
        public int RentalId { get; set; }

        [Required(ErrorMessage = "Customer is Required")]
        public Nullable<int> CustomerId { get; set; }


        [Required(ErrorMessage = "Car is Required")]
        public Nullable<int> CarId { get; set; }

        [Display(Name = "Date Rented")]
        [DisplayFormat(DataFormatString = "{0:MM.dd.yyyy}", ApplyFormatInEditMode = true)]
        [Required(ErrorMessage = "Date Rented is Required")]
        public Nullable<System.DateTime> DateRented { get; set; }

        [Display(Name = "Date Returned")]
        [DisplayFormat(DataFormatString = "{0:MM.dd.yyyy}", ApplyFormatInEditMode = true)]

        public Nullable<System.DateTime> DateReturned { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
